### ISSUE TITLE
Chrome "mixed content" error breaks Blip after 1 second

### ISSUE THREAD

**Issue by nhooey** [apenwarr/blip#10]
In at least Mac Chrome 51.0.2704.103 (64-bit), Blip only shows valid graph points for the first second after a refresh, then shows a max-latency red line after that. Refreshing always fixes it for a second, then it breaks again.

The JavaScript console says `Mixed content: The page was loaded over HTTPS, but requested in insecure endpoint` coming from `jquery.min.js`.

In Safari, Blip works fine without issue.

**Comment by dgentry** [comment]
Here's what that looks like.
![blip-all-red](https://cloud.githubusercontent.com/assets/875294/16993860/fc92870e-4e59-11e6-8d75-88725879e518.jpg)

**Comment by sourcejedi** [comment]
Thanks! Knowing this, I can switch the URL from `https://` to `http://` and have it work in Chrome

**Comment by cbowns** [comment]
`https` now fails in Safari 10.0.2 on OS X 10.11.6:

(this connection is up and working, btw)

<img width="833" alt="screen shot 2017-01-10 at 6 53 17 pm" src="https://cloud.githubusercontent.com/assets/474/21833307/16512b74-d766-11e6-81b4-850e1ac0e58b.png">

**Comment by nolanw** [comment]
https fails on iOS too, making it hard to use this excellent tool on iPhones and iPads. Booping over to http works great though!

**Comment by Omicron18** [comment]
On Brave, even after I edited the url to `http://`, I got  auto-redirected to `https://`, which breaks after a second.  I had to turn off `Upgrade connections to HTTPS` on `brave://settings`.

**Comment by danielcompton** [comment]
I think switching to https://mlab-ns.appspot.com/ndt_ssl?policy=all might help here, it gives the FQDNs as dash separated so that they can be contacted over HTTPS. https://github.com/m-lab/mlab-ns/pull/51

**Comment by Yostage** [comment]
I was able to make this work by enabling mixed content like this https://stackoverflow.com/questions/18321032/how-to-get-chrome-to-allow-mixed-content

**Comment by 33b5e5** [comment]
This essentially doesn't work for me in Brave, Firefox or Edge on Windows. I get a few pings then it looks like what @dgentry shared above.

I'm on gig fiber with traffic shaping in place to prevent buffer bloat (via OPNsense), so I have very low latency even on loaded connections. Still, was curious to try this tool. Not curious enough to turn off https or mixed-content warnings though.

**Comment by akhiljalagam** [comment]
same in firefox

**Comment by dtolnay** [comment]
In Firefox, it works after you "disable protection" under the padlock icon.

<img src="https://user-images.githubusercontent.com/1940490/211881918-50bb5349-20fd-43dc-8e9d-38ed2b9e4020.png" width="500">

**Comment by Incog5** [comment]
you can also do this in chrome: click on the padlock icon, site settings, set "Insecure content" to allow

**Comment by apenwarr** [comment]
fixed in master! Should show up on the original server soon. Meanwhile, a different test server that doesn't seem to trigger the problem: http://blip.apenwarr.ca/
