### ISSUE TITLE
Pings to gstatic fail

### ISSUE THREAD

**Issue by manugarri** [apenwarr/blip#14]
on my browser, pings to gstatic seem to fail (and give the dreaded packet loss red dots). Seems like my browser cant reach the domain?

Here you can see a screenshot of the network errors. Im not sure if this is a country/isp/router/browser issue.

![image](https://user-images.githubusercontent.com/3670355/199678703-7b3391a6-a8d0-41a8-ae60-4fb4dae7b84e.png)

**Comment by daviewales** [comment]
I'm getting something similar, but I'm wondering if it's the mlab calls.

Looking at the code, blip fetches a list of mlab test URLs from here:
https://mlab-ns.appspot.com/ndt?policy=all

then picks one to test against. Mine was:
http://ndt-iupui-mlab2-bru05.mlab-oti.measurement-lab.org:7123/

However, when I put that URL directly into my browser, I get 'Firefox can’t establish a connection to the server'.
I get the same thing when I try the other mlab test URLs.

**Comment by apenwarr** [comment]
chances are that you loaded gfblip from an https:// url rather than an http:// url. Try again with the new version, which works around this problem.

**Comment by daviewales** [comment]
That seems to have fixed it, at least for me. Thanks!
