### ISSUE TITLE
Inconsistency of the host for the green lines

### ISSUE THREAD

**Issue by Joshfindit** [apenwarr/blip#16]
Overall the UI makes sense, but I'm confused about how the hosts are chosen.

On FireFox on Windows it might ping `gstatic.com`
On Brave on the same machine it chose `192.168.3.254` (which is the wrong subnet for the LAN) and `Atlanta, US`. Both show as solid red bars.

On Safari on macOS it chose a gateway IP on the correct LAN subnet

On Safari on iOS it chose the same LAN gateway IP and then Brussels, BE

**Comment by apenwarr** [comment]
I spend some time hacking on blip over the holidays and the host selection should now be much improved. Let me know if it's better for you now!
