### ISSUE TITLE
https in repo summary

### ISSUE THREAD

**Issue by andykais** [apenwarr/blip#17]
Awesome little tool! I noticed that your site url that is being passed around hackernews is `http://` instead of `https://`. Github gives you SSL for free on their static sites, and it looks like your custom domain has ssl support as well (https://gfblip.appspot.com/). Maybe just change the url in the summary to be `https://gfblip.appspot.com` rather than `http://gfblip.appspot.com`?

**Comment by andykais** [comment]
related, github has the ability to redirect HTTP to HTTPS on custom domains with a setting flag described here https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site. Though with that setting I am not exactly sure how it works!

**Comment by andykais** [comment]
oh, hmm...actually it looks like SSL messes with the site. Lots of these errors
```
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '<URL>'. This request has been blocked; the content must be served over HTTPS.
```
It seems that there is more going on here that I dont quite understand :sweat_smile:.

It seems like its these calls:
`http://192.168.0.xxx:8999/generate_204'`

**Comment by giovanniberti** [comment]
HTTPS issues are also mentioned in #10

**Comment by drheld** [comment]
This is mostly fixed now. I think there's one last call which I sent https://github.com/apenwarr/blip/pull/27 for.

**Comment by apenwarr** [comment]
Yup, seems fixed now! Thanks to drheld for all the help (and, uh, motivation :))
