### ISSUE TITLE
Latency patterns change with browser

### ISSUE THREAD

**Issue by willsthompson** [apenwarr/blip#19]
I could be misunderstanding something about expected browser behavior, but there is pattern of green outlier latencies that occur at regular intervals, and the characteristics of those outliers change between Safari and Firefox. The behavior is repeatable if I switch back and forth between browsers. I don't have an explanation for the outliers either, but I thought it was odd that the patterns aren't roughly equivalent on different browsers on the same machine.

Safari:
 
<img width="800" alt="Screen Shot 2022-11-11 at 10 41 31 AM" src="https://user-images.githubusercontent.com/1315884/201414934-8132bb8a-af2a-42e6-b234-6a03648a903c.png">

Firefox:

<img width="800" alt="Screen Shot 2022-11-11 at 1 15 44 PM" src="https://user-images.githubusercontent.com/1315884/201414961-ebcd9ca3-d1cd-4841-9630-0d66b4506e03.png">

**Comment by apenwarr** [comment]
Chances are, this is actually your browser acting weird and adding latency sometimes. Try running it with all extensions disabled? 

I think it is correct for blip to show these differences between results. It's trying to measure actual latency of retrieving stuff into your browser, so if your browser is randomly adding latency, that's the truth.

Note: we just fixed a few longstanding blip bugs and switched to the new(er) javascript fetch() api which might change a few things. Please try out the latest version.
