### ISSUE TITLE
Timeouts on chromium-based browsers - workaround or document?

### ISSUE THREAD

**Issue by mcint** [apenwarr/blip#20]
On chromium-based browsers, browser will revert to not sharing timing information with the javascript running for https://gfblip.appspot.com/. Can this be fixed? In general? Or with manual fiddling per session? Or not at all?

No matter which answer is the case, can it be documented, e.g. on the readme? This is a great debugging tool, but having flaky performance makes it hard to ever recommend again, even if it's due to browser security moving targets.

**Comment by apenwarr** [comment]
I'm not sure what kind of timing information you mean. Is this the microseconds-level timing to defend against memory privacy attacks? That doesn't really affect blip, which runs at the milliseconds to hundreds of milliseconds range.
