### ISSUE TITLE
resource: A server with the specified hostname could not be found.

### ISSUE THREAD

**Issue by HackettLai** [apenwarr/blip#29]
I keep seeing error on hostname could not be found for https://ndt-iupui-mlab2-hnl01.mlab-oti.measurement-lab.org/ and https://{my ip}:8999/generate_204

how can I fix this?

![CleanShot 2024-04-15 at 11 01 21](https://github.com/apenwarr/blip/assets/56993446/eafcca52-1fcf-4f18-a0cc-23a71b627eea)

**Comment by drheld** [comment]
I just noticed this -- going to take a look.

**Comment by drheld** [comment]
Now fixed on the live version. I'll send a pull request.
