### ISSUE TITLE
graphics look bad on desktop

### ISSUE THREAD

**Issue by adavies42** [apenwarr/blip#4]
![screen shot 2013-05-13 at 11 54 25 pm](https://f.cloud.github.com/assets/91266/499555/34aff342-bc4a-11e2-91e7-06463194f4ec.png)

chrome 26.0.1410.65 on os x 10.7.5 at 2560 x 1440 in full-screen mode

(hopefully the system doesn't shrink the screen-shot—the problem is that all the blips, and the numbers at the side, are incredibly fuzzy, like they're bad JPEGs or were upscaled with a really naive algorithm or something)

**Comment by apenwarr** [comment]
Finally fixed enough code that I could upload the version that fixed this.  Only 4 years late!

**Comment by verhovsky** [comment]
Still looks pretty blurry on my macbook air.
