### ISSUE TITLE
numbers disappear in safari

### ISSUE THREAD

**Issue by adavies42** [apenwarr/blip#7]
safari 6.0.4/lion 10.7.5

open blip in safari, create a new tab, switch back to blip. y axis labels are gone. doesn’t happen in chrome 26.0.1410.65.

![screen shot 2013-05-23 at 8 43 52 pm](https://f.cloud.github.com/assets/91266/558121/9dc4bfca-c40b-11e2-9af5-673b182c1200.png)

**Comment by apenwarr** [comment]
New version uses slightly different rendering that should fix this.
