### ISSUE TITLE
Targets used for http ping are cacheable by http proxies

### ISSUE THREAD

**Issue by sourcejedi** [apenwarr/blip#8]
My Polipo proxy is caching at least the the apenwar.ca target.  Because blip shows latency <50ms when  the browser uses the proxy, and 200ms otherwise.

Polipo is generally compliant.  I think setting `Cache-Control: no-store` on the server should work.  Alternatively on the _client_ side, setting `Pragma: no-cache` should work (but I don't know if XHR lets you).

Http cache reference: https://www.mnot.net/cache_docs/#CONTROL

**Comment by apenwarr** [comment]
Now using ndt servers.  The result is a little weird, but it should avoid this problem.
